# if "true" (default) then groups will be merged by name to have the same users. if "false" then an error will
# be shown in the log but the output yaml will ONLY use the first group of the name that it finds.
merge: true
# if the groups are provided from openshift as with the "-g" option keycloak-sync will work so that
# the state of keycloak and any changes/groups that were added otherwise will be gone. this _will_ delete
# any other type of added groups. setting this to "true" means that keycloak is the single overriding source
# of truth for groups that are found. warning: if you name a group the same as a group that came from keycloak
# and put users in it this procedure will clear/overwrite that group.
prune: true
# a list of realms to read user and group from
realms:
  # the realm that will be used as the source for users and groups. this is the name of the realm
  # as given in keycloak/sso
- name: sso
  # the url to the root of the keycloak/sso instance
  url: https://auth-sso.apps-crc.testing
  # allows the setting of ssl-verification for the remote host. set
  # to false when the remote host is insecure
  ssl-verify: false
  # credentials for the read-only client
  client-id: sync-client
  client-secret: edc39d4b-3fdf-4ea5-b8c7-853489224817
  # a list of values to search for the username. this should match the configuration value used when
  # adding an oidc identity provider as in the openshift documentation for the resource type "OAuth".
  # the first match is used. if no values are provided (empty or missing list) then the value of the
  # "Username" from Keycloak is used.\
  # TODO: this does not work yet
  preferred-username:
  - preferred_username
  - username
  - email
  # groups to synchronize, empty or null if all groups
  groups: []
  # aliases describe a map of group names _in keycloak_ to a map of group
  # names as you want to see them, aliases override prefix/suffix values
  # so if you want an alias with a prefix/suffix set it in the prefix name
  aliases:
    developers: sso-developers-dev
  # if a group name doesn't have an alias the prefix is applied to the
  # group name. a prefix of "sso-" turns a keycloak group "dev" to
  # "sso-dev"
  group-prefix: "sso-"
  # if a group name doesn't have an alias the suffix is applied to the
  # group name. a suffix of "_dev" turns a keycloak group "admin" to
  # "admin_dev"
  group-suffix: "-dev"
  # if this is set to true then users no longer in the group
  # will be pruned out. if it is set to false then any old
  # users will be retained and only new users will be added.
  prune: true