# if the groups are provided from openshift as with the "-g" option keycloak-sync will work so that
# the state of keycloak and any changes/groups that were added otherwise will be gone. this _will_ delete
# any other type of added groups. setting this to "true" means that keycloak is the single overriding source
# of truth for groups that are found. warning: if you name a group the same as a group that came from keycloak
# and put users in it this procedure will clear/overwrite that group.
prune: true
# a list of realms to read user and group from
realms:
  # the realm that will be used as the source for users and groups. this is the name of the realm
  # as given in keycloak/sso. this is case sensitive.
- name: sso
  # the url to the root of the keycloak/sso instance
  url: http://localhost:8080
  # allows the setting of ssl-verification for the remote host. set
  # to false when the remote host is insecure
  ssl-verify: false
  # credentials for the read-only client. this is required if no `user` is configured
  client:
    client-id: sync-client
    client-secret: d0a8b5cb-edfe-4e15-83d0-3446850310a7
  # credentials for a user with the capacity to query the given realm.. this is required if no `client` is configured
  user:
    username: admin
    password: admin
    # a realm is required if the realm is different than the realm name of current realm.
    # this is useful if the user is in another realm and has permissions on the current realm.
    realm: master
  # a list of values to search for the username. this should match the configuration value used when
  # adding an oidc identity provider as in the openshift documentation for the resource type "OAuth".
  # the first match is used. if no values are provided (empty or missing list) then the value of the
  # "Username" from Keycloak is used.\
  # TODO: this does not work yet
  preferred-username:
  - preferred_username
  - username
  - email
  # groups to synchronize, empty or null if all groups. this is the group name in keycloak/sso and not the
  # name after the alias or prefix/suffix. if this option is used individual queries will be made to the
  # keycloak server for each group name. this finds groups if they are a subgroup even if "subgroups" is set
  # to false.
  groups: []
  # groups to block, empty or null allows all groups. this is the group name in keycloak/sso and not the
  # name after the alias or prefix/suffix. this option will hit subgroups with the same name in different
  # trees so that something like "test" will block both "/admins/test" and "/developers/test"
  block-groups: []
  # groups to block after the final name is calculated. this removes groups after the final name is calculated
  # so that if there were three hierarchies like /admins/stage, /developers/stage, and /testers/stage and you
  # the intent was to have admins.stage and developers.stage but not testers.stage you could put "stage" as
  # the value in the groups item and then block "testers.stage" here. This can also be used if a subgroup has
  # a lot of subgroups itself that are wanted but not the intermediary group like "/admins/databases/{pg,sql,oracle}"
  # and the groups "admins" and "admins.databases.pg", "admins.databases.sql", and "admins.databases.oracle" are
  # needed but not "admins.databases"
  block-group-names: []
  # aliases describe a map of group names _in keycloak_ to a map of group
  # names as you want to see them, aliases override prefix/suffix values
  # so if you want an alias with a prefix/suffix set it in the prefix name
  aliases:
    developers: sso-developers-dev
  # if a group name doesn't have an alias the prefix is applied to the
  # group name. a prefix of "sso-" turns a keycloak group "dev" to
  # "sso-dev"
  group-prefix: "sso-"
  # if a group name doesn't have an alias the suffix is applied to the
  # group name. a suffix of "_dev" turns a keycloak group "admin" to
  # "admin_dev"
  group-suffix: "-dev"
  # if true then walk the group tree and add subgroups as well
  subgroups: true
  # if true then "promote" users by adding them to parent groups as well so that the flat nature of the
  # openshift groups carries the same semantic value as the hierarchical structure in keycloak
  subroup-promote-users: true
  # if true then add the parent group of a subgroup to the name structure so that "administrators/db" becomes
  # "administrators" and "administrators.db". if the group has an alias name set this will override the alias.
  # this step happens before prefix and suffix are applied so it would be "prefixgroup.child.childsuffix" or
  # something like "sso-administrators.databaseAdministrators-dev"
  subgroup-concat-names: true
  # the value of the characters between a group and its children. the default value is ".".
  subgroup-separator: "."